version: 2
jobs:
   build:
     docker:
       - image: circleci/node:8
     working_directory: ~/repo
     steps:
       - checkout
       - run: sudo apt-get install gconf-service libasound2 libatk1.0-0 libc6 libcups2 libdbus-1-3 libgconf-2-4 libgtk-3-0 libnspr4 libxcomposite1 libxcursor1 libxi6 libxrandr2 libxss1 libxtst6 fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget
       - restore_cache:
           keys:
             - npm-dev-cache-{{ checksum "yarn.lock" }}
             - npm-dev-cache-
       - run: make install
       - run: make lint
       - run: make install_chrome
       - run: make tests
       - save_cache:
           key: npm-dev-cache-{{ checksum "yarn.lock" }}
           paths:
             - node_modules
   deploy:
     docker:
       - image: circleci/node:8
     working_directory: ~/repo
     steps:
       - checkout
       - restore_cache:
           keys:
             - npm-cache-{{ checksum "yarn.lock" }}
             - npm-cache-
       - run: make install_production
       - run: make artifact
       - run: make upload
       - save_cache:
           key: npm-cache-{{ checksum "yarn.lock" }}
           paths:
             - node_modules
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
