version: 2
jobs:
   build:
     docker:
       - image: circleci/node:8
     working_directory: ~/repo
     steps:
       - checkout
       - apt-get install libx11-xcb1
       - restore_cache:
           keys:
             - npm-dev-cache-{{ checksum "yarn.lock" }}
             - npm-dev-cache-
       - run: make install
       - run: make lint
       - run: make install_chrome
       - run: make tests
       - save_cache:
           key: npm-dev-cache-{{ checksum "yarn.lock" }}
           paths:
             - node_modules
   deploy:
     docker:
       - image: circleci/node:8
     working_directory: ~/repo
     steps:
       - checkout
       - restore_cache:
           keys:
             - npm-cache-{{ checksum "yarn.lock" }}
             - npm-cache-
       - run: make install_production
       - run: make artifact
       - run: make upload
       - save_cache:
           key: npm-cache-{{ checksum "yarn.lock" }}
           paths:
             - node_modules
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
